### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by xMOD3** [Dew3/TikTok-Username-Checker#1]
I installed all the requirements
It gives me this

================================================================================
"webkit" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================

**Comment by Dew3** [comment]
From the README: "After installing TikTokApi the console may alert another package is required. Install it." You should just do 'pip3 install playwright' and you should be on your way. If this doesn't work get back to me and I will look further into it. I have reopened this issue in case this fix fails.

**Comment by xMOD3** [comment]
still not working
I also installed all the libraries

**Comment by xMOD3** [comment]
https://prnt.sc/wjhgaq 
https://prnt.sc/wjhlme
This is when I run the script

**Comment by Dew3** [comment]
> still not working
> 
> I also installed all the libraries

It may be because you are installing playwright with a proxy or VPN. See: https://github.com/davidteather/TikTok-Api/issues/370. Get back to me if this doesn't work. Very curious as I haven't seen this before. I will do some testing when I get back home and on my computer.

**Comment by xMOD3** [comment]
now it works but the problem is all the usernames are Not taken when i tried to register them they're all taken
Also, do you have discord?

**Comment by Dew3** [comment]
I'm currently out of town but I made this quick server on mobile and will continue to update it in the future: https://discord.gg/x4Xn7UfDJ6. I can help you on discord. I will be closing this issue now.
