### ISSUE TITLE
Wont check names anyore

### ISSUE THREAD

**Issue by pitfaII** [Dew3/TikTok-Username-Checker#7]
I downloaded this yesterday and it was working just fine but now it displays a weird string of code when i run the file but when i run it in command prompt it says put names in usernames.txt but i have usernames in it

**Comment by Dew3** [comment]
Any way you could respond to this thread with screenshots of the string code error as well as maybe a screenshot of your usernames.txt; Perhaps a line of code was typed incorrectly or wrong file name. Very hard to provide a solution with limited explanation.

**Comment by jaxynn** [comment]
said everything in my list want taken lmao. idk if it was a problem on my end but i thought i was post it anyway. pls help 
![image](https://user-images.githubusercontent.com/87832304/132185397-848816ff-0723-42ef-9652-0cda73a55e87.png)

**Comment by Dew3** [comment]
> said everything in my list want taken lmao. idk if it was a problem on my end but i thought i was post it anyway. pls help
> ![image](https://user-images.githubusercontent.com/87832304/132185397-848816ff-0723-42ef-9652-0cda73a55e87.png)

It's most likely because you are using way too many names and therefore hitting rate limits on TikTok's end. I'd recommend only doing a couple hundred at a time in order to not get rate limited. Wait 24 hours or a few days and it should work again. Instead of 5000 names try using only 100 at a time.

**Comment by bpbpbme** [comment]
I'm having the same problem with with just over 100 usernames. 
![Screenshot 2021-09-12 184916](https://user-images.githubusercontent.com/90560711/132995953-987fa380-46fe-4b2d-b81f-9969f53d6a3b.png)

**Comment by Dew3** [comment]
Only thing else I could tell you without physically seeing the problem would be to re copy the code and potentially uninstall and reinstall packages if needed. Update me on how it goes.

**Comment by lsoz** [comment]
is there any checker that works currently

**Comment by Dew3** [comment]
> is there any checker that works currently

This checker works. Please take the time to install all packages required and follow the README for directions on how to use.

**Comment by ImpulseHD** [comment]
I installed all the packages, the one from tiktokApi and the other one they told me to install and obviously all the ones in the script but it still doesn't work.

**Comment by ImpulseHD** [comment]
> I installed all the packages, the one from tiktokApi and the other one they told me to install and obviously all the ones in the script but it still doesn't work.

I found the problem, just replace line 41 with "user = api.get_user_object(username)"

**Comment by ZoOoM663** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/115731329/220260624-6df0e8ac-751b-4320-8a7f-095fdf8a9f0f.png)



it didn't work with me why?

**Comment by ZoOoM663** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/115731329/220260996-202b596c-ebe2-47d9-a35f-0b3787b5237c.png)
